sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pghanwat/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pghanwat/docker-react npm run test
